# Generated by Django 4.2.20 on 2025-04-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRVisionApp', '0002_privatekey_delete_multipleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekey',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
