# Generated by Django 4.2.20 on 2025-04-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRVisionApp', '0003_privatekey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='private_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
