# Generated by Django 4.2.20 on 2025-04-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QRVisionApp', '0004_alter_privatekey_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('amount_before_tax', models.IntegerField(blank=True, null=True)),
                ('total_invoice_amount', models.IntegerField(blank=True, null=True)),
                ('tax_amount', models.IntegerField(blank=True, null=True)),
                ('tax_number', models.CharField(max_length=100)),
                ('plain_text', models.CharField(blank=True, max_length=255)),
                ('private_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRVisionApp.privatekey')),
            ],
        ),
    ]
