# Generated by Django 4.2.20 on 2025-04-15 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QRVisionApp', '0006_alter_invoice_amount_before_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
