# Generated by Django 4.2.20 on 2025-04-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRVisionApp', '0007_invoice_created_at_privatekey_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cipher_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
