# Generated by Django 4.2.20 on 2025-04-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRVisionApp', '0008_invoice_cipher_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cipher_text',
            field=models.CharField(max_length=255),
        ),
    ]
